/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/4F3PAfsH7XA
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Card, CardContent } from "@/components/ui/card"

export function channel_info() {
  return (
    <div className="flex flex-col h-screen">
      <header className="bg-background border-b px-4 py-3 flex items-center gap-4">
        <div className="flex items-center gap-2">
          <BotIcon className="w-6 h-6 text-primary" />
          <h1 className="text-xl font-bold">YouTube Chatbot</h1>
        </div>
        <div className="flex-1 relative">
          <Input type="search" placeholder="Search YouTube..." className="pl-8 pr-12 h-10 rounded-full" />
          <Button type="submit" variant="ghost" size="icon" className="absolute right-2 top-1/2 -translate-y-1/2">
            <SearchIcon className="w-5 h-5 text-muted-foreground" />
          </Button>
        </div>
      </header>
      <div className="flex-1 overflow-auto p-4 grid gap-4">
        <div className="flex items-start gap-4">
          <Avatar className="w-8 h-8 border">
            <AvatarImage src="/placeholder-user.jpg" />
            <AvatarFallback>CB</AvatarFallback>
          </Avatar>
          <div className="grid gap-4 flex-1">
            <Card>
              <CardContent>
                <div className="grid gap-2">
                  <div className="flex items-center justify-between">
                    <div className="font-medium">
                      A video tutorial on using React Hooks effectively in web development projects
                    </div>
                    <div className="text-xs text-muted-foreground">2:47 PM</div>
                  </div>
                  <div className="grid md:grid-cols-[150px_1fr] gap-4">
                    <img src="/placeholder.svg" alt="Thumbnail" className="rounded-md object-cover aspect-video" />
                    <div className="grid grid-cols-3 gap-4">
                      <div className="font-medium line-clamp-2">
                        React Hooks Crash Course
                        <div className="text-sm text-muted-foreground">
                          <div className="flex items-center gap-2">
                            <ClockIcon className="w-4 h-4" />
                            <span>25:17</span>
                          </div>
                          <div className="flex items-center gap-2">
                            <EyeIcon className="w-4 h-4" />
                            <span>320K views</span>
                          </div>
                          <div className="flex items-center gap-2">
                            <UserIcon className="w-4 h-4" />
                            <span>Web Dev Simplified</span>
                          </div>
                        </div>
                      </div>
                      <div>
                        <div className="font-medium">Audience Sentiment</div>
                        <div className="text-sm text-muted-foreground">
                          Analyze the audience's reaction and sentiment towards the video content.
                        </div>
                      </div>
                      <div>
                        <div className="font-medium">Improvement Tips</div>
                        <div className="text-sm text-muted-foreground">
                          Provide suggestions on how to improve the video for better engagement.
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardContent>
                <div className="grid gap-2">
                  <div className="flex items-center justify-between">
                    <div className="font-medium">
                      A video tutorial on using React Hooks effectively in web development projects
                    </div>
                    <div className="text-xs text-muted-foreground">2:47 PM</div>
                  </div>
                  <div className="grid md:grid-cols-[150px_1fr] gap-4">
                    <img src="/placeholder.svg" alt="Thumbnail" className="rounded-md object-cover aspect-video" />
                    <div className="grid grid-cols-3 gap-4">
                      <div className="font-medium line-clamp-2">
                        React Hooks Crash Course
                        <div className="text-sm text-muted-foreground">
                          <div className="flex items-center gap-2">
                            <ClockIcon className="w-4 h-4" />
                            <span>25:17</span>
                          </div>
                          <div className="flex items-center gap-2">
                            <EyeIcon className="w-4 h-4" />
                            <span>320K views</span>
                          </div>
                          <div className="flex items-center gap-2">
                            <UserIcon className="w-4 h-4" />
                            <span>Web Dev Simplified</span>
                          </div>
                        </div>
                      </div>
                      <div>
                        <div className="font-medium">Audience Sentiment</div>
                        <div className="text-sm text-muted-foreground">
                          Analyze the audience's reaction and sentiment towards the video content.
                        </div>
                      </div>
                      <div>
                        <div className="font-medium">Improvement Tips</div>
                        <div className="text-sm text-muted-foreground">
                          Provide suggestions on how to improve the video for better engagement.
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardContent>
                <div className="grid gap-2">
                  <div className="flex items-center justify-between">
                    <div className="font-medium">
                      A video tutorial on using React Hooks effectively in web development projects
                    </div>
                    <div className="text-xs text-muted-foreground">2:47 PM</div>
                  </div>
                  <div className="grid md:grid-cols-[150px_1fr] gap-4">
                    <img src="/placeholder.svg" alt="Thumbnail" className="rounded-md object-cover aspect-video" />
                    <div className="grid grid-cols-3 gap-4">
                      <div className="font-medium line-clamp-2">
                        React Hooks Crash Course
                        <div className="text-sm text-muted-foreground">
                          <div className="flex items-center gap-2">
                            <ClockIcon className="w-4 h-4" />
                            <span>25:17</span>
                          </div>
                          <div className="flex items-center gap-2">
                            <EyeIcon className="w-4 h-4" />
                            <span>320K views</span>
                          </div>
                          <div className="flex items-center gap-2">
                            <UserIcon className="w-4 h-4" />
                            <span>Web Dev Simplified</span>
                          </div>
                        </div>
                      </div>
                      <div>
                        <div className="font-medium">Audience Sentiment</div>
                        <div className="text-sm text-muted-foreground">
                          Analyze the audience's reaction and sentiment towards the video content.
                        </div>
                      </div>
                      <div>
                        <div className="font-medium">Improvement Tips</div>
                        <div className="text-sm text-muted-foreground">
                          Provide suggestions on how to improve the video for better engagement.
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
        <div className="flex items-start gap-4">
          <Avatar className="w-8 h-8 border">
            <AvatarImage src="/placeholder-user.jpg" />
            <AvatarFallback>CB</AvatarFallback>
          </Avatar>
          <div className="grid gap-4 flex-1">
            <Card>
              <CardContent>
                <div className="grid gap-2">
                  <div className="flex items-center justify-between">
                    <div className="font-medium">
                      A video tutorial on using React Hooks effectively in web development projects
                    </div>
                    <div className="text-xs text-muted-foreground">2:47 PM</div>
                  </div>
                  <div className="grid md:grid-cols-[150px_1fr] gap-4">
                    <img src="/placeholder.svg" alt="Thumbnail" className="rounded-md object-cover aspect-video" />
                    <div className="grid grid-cols-3 gap-4">
                      <div className="font-medium line-clamp-2">
                        React Hooks Crash Course
                        <div className="text-sm text-muted-foreground">
                          <div className="flex items-center gap-2">
                            <ClockIcon className="w-4 h-4" />
                            <span>25:17</span>
                          </div>
                          <div className="flex items-center gap-2">
                            <EyeIcon className="w-4 h-4" />
                            <span>320K views</span>
                          </div>
                          <div className="flex items-center gap-2">
                            <UserIcon className="w-4 h-4" />
                            <span>Web Dev Simplified</span>
                          </div>
                        </div>
                      </div>
                      <div>
                        <div className="font-medium">Audience Sentiment</div>
                        <div className="text-sm text-muted-foreground">
                          Analyze the audience's reaction and sentiment towards the video content.
                        </div>
                      </div>
                      <div>
                        <div className="font-medium">Improvement Tips</div>
                        <div className="text-sm text-muted-foreground">
                          Provide suggestions on how to improve the video for better engagement.
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardContent>
                <div className="grid gap-2">
                  <div className="flex items-center justify-between">
                    <div className="font-medium">
                      A video tutorial on using React Hooks effectively in web development projects
                    </div>
                    <div className="text-xs text-muted-foreground">2:47 PM</div>
                  </div>
                  <div className="grid md:grid-cols-[150px_1fr] gap-4">
                    <img src="/placeholder.svg" alt="Thumbnail" className="rounded-md object-cover aspect-video" />
                    <div className="grid grid-cols-3 gap-4">
                      <div className="font-medium line-clamp-2">
                        React Hooks Crash Course
                        <div className="text-sm text-muted-foreground">
                          <div className="flex items-center gap-2">
                            <ClockIcon className="w-4 h-4" />
                            <span>25:17</span>
                          </div>
                          <div className="flex items-center gap-2">
                            <EyeIcon className="w-4 h-4" />
                            <span>320K views</span>
                          </div>
                          <div className="flex items-center gap-2">
                            <UserIcon className="w-4 h-4" />
                            <span>Web Dev Simplified</span>
                          </div>
                        </div>
                      </div>
                      <div>
                        <div className="font-medium">Audience Sentiment</div>
                        <div className="text-sm text-muted-foreground">
                          Analyze the audience's reaction and sentiment towards the video content.
                        </div>
                      </div>
                      <div>
                        <div className="font-medium">Improvement Tips</div>
                        <div className="text-sm text-muted-foreground">
                          Provide suggestions on how to improve the video for better engagement.
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardContent>
                <div className="grid gap-2">
                  <div className="flex items-center justify-between">
                    <div className="font-medium">
                      A video tutorial on using React Hooks effectively in web development projects
                    </div>
                    <div className="text-xs text-muted-foreground">2:47 PM</div>
                  </div>
                  <div className="grid md:grid-cols-[150px_1fr] gap-4">
                    <img src="/placeholder.svg" alt="Thumbnail" className="rounded-md object-cover aspect-video" />
                    <div className="grid grid-cols-3 gap-4">
                      <div className="font-medium line-clamp-2">
                        React Hooks Crash Course
                        <div className="text-sm text-muted-foreground">
                          <div className="flex items-center gap-2">
                            <ClockIcon className="w-4 h-4" />
                            <span>25:17</span>
                          </div>
                          <div className="flex items-center gap-2">
                            <EyeIcon className="w-4 h-4" />
                            <span>320K views</span>
                          </div>
                          <div className="flex items-center gap-2">
                            <UserIcon className="w-4 h-4" />
                            <span>Web Dev Simplified</span>
                          </div>
                        </div>
                      </div>
                      <div>
                        <div className="font-medium">Audience Sentiment</div>
                        <div className="text-sm text-muted-foreground">
                          Analyze the audience's reaction and sentiment towards the video content.
                        </div>
                      </div>
                      <div>
                        <div className="font-medium">Improvement Tips</div>
                        <div className="text-sm text-muted-foreground">
                          Provide suggestions on how to improve the video for better engagement.
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </div>
  )
}

function BotIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 8V4H8" />
      <rect width="16" height="12" x="4" y="8" rx="2" />
      <path d="M2 14h2" />
      <path d="M20 14h2" />
      <path d="M15 13v2" />
      <path d="M9 13v2" />
    </svg>
  )
}


function ClockIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>
  )
}


function EyeIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7Z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}


function SearchIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function UserIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}
