/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/bjLEoGda2tG
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card } from "@/components/ui/card"
import Link from "next/link"
import { Separator } from "@/components/ui/separator"
import { JSX, SVGProps } from "react"

export function video_info() {
  return (
    <Card className="w-full max-w-2xl">
      <div className="grid grid-cols-[180px_1fr] gap-4">
        <div>
          <img
            src="/placeholder.svg"
            alt="Video Thumbnail"
            width={320}
            height={180}
            className="rounded-lg object-cover"
          />
        </div>
        <div className="grid grid-cols-2 gap-4">
          <div className="grid gap-2">
            <div className="flex items-center gap-2">
              <LinkIcon className="h-4 w-4" />
              <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
                Watch the full video
              </Link>
            </div>
            <div className="flex items-center gap-2">
              <LinkIcon className="h-4 w-4" />
              <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
                View the creator's channel
              </Link>
            </div>
            <div className="flex items-center gap-2">
              <LinkIcon className="h-4 w-4" />
              <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
                Read the video description
              </Link>
            </div>
          </div>
          <div className="flex items-center gap-4 text-sm text-muted-foreground grid grid-cols-2 gap-4">
            <div className="flex justify-center items-center gap-1">
              <EyeIcon className="w-4 h-4 mr-1" />
              320K views
            </div>
            <div className="flex items-center gap-1">
              <ThumbsUpIcon className="w-4 h-4 text-green-500" />
              92%
            </div>
            <div className="flex justify-center items-center gap-1">
              <ClockIcon className="w-4 h-4 mr-1" />
              2 hours ago
            </div>
            <div className="flex items-center gap-1">
              <ShareIcon className="w-4 h-4 mr-1" />
              Share
            </div>
          </div>
        </div>
      </div>
      <Separator className="my-6" />
      <div className="space-y-4">
        <h4 className="text-lg font-medium text-center">
          Building a successful YouTube channel in 2023, covering strategy, content creation, and growth tactics.
        </h4>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 justify-center">
          <div className="text-center border-r pr-4">
            <h5>Description</h5>
            <p>
              This video provides a comprehensive guide on building a successful YouTube channel in 2023, covering key
              strategies, content creation best practices, and growth tactics to help creators achieve their goals.
            </p>
          </div>
          <div className="text-center border-r pr-4">
            <h5 className="text-sm font-medium">Key Points</h5>
            <ul className="space-y-1 text-sm text-muted-foreground list-disc pl-4">
              <li>Identify your niche and target audience</li>
              <li>Produce high-quality, consistent content</li>
              <li>Leverage YouTube's algorithm and trends</li>
              <li>Engage with your community</li>
              <li>Diversify your revenue streams</li>
            </ul>
          </div>
          <div className="text-center border-r pr-4">
            <h5 className="text-sm font-medium">Sentiment</h5>
            <p className="text-sm text-muted-foreground">
              Viewers are excited and inspired by the practical tips and strategies shared in the video. The comments
              section is filled with positive feedback and users sharing their own YouTube growth journeys.
            </p>
          </div>
          <div className="text-center">
            <h5 className="text-sm font-medium">Target Audience</h5>
            <p className="text-sm text-muted-foreground">
              Aspiring YouTube creators, small business owners, and content creators looking to grow their channels.
            </p>
          </div>
        </div>
      </div>
    </Card>
  )
}

function ClockIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>
  )
}


function EyeIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7Z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}


function LinkIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71" />
      <path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71" />
    </svg>
  )
}


function ShareIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8" />
      <polyline points="16 6 12 2 8 6" />
      <line x1="12" x2="12" y1="2" y2="15" />
    </svg>
  )
}


function ThumbsUpIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7 10v12" />
      <path d="M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2h0a3.13 3.13 0 0 1 3 3.88Z" />
    </svg>
  )
}
