
'use client'
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ZLFXHSpPSGg
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Card, CardHeader, CardTitle, CardContent} from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"
//import { useState } from "react"


export function AboutSection() {
  //const [data,setData]=useState({})
  //const getData = async ()=> {const response= await fetch()}
  return (
    <Card className="w-full max-w-md">
      <CardHeader className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <Avatar className="w-12 h-12">
            <AvatarImage src="/placeholder-user.jpg" />
            <AvatarFallback>YT</AvatarFallback>
          </Avatar>
          <div>
            <CardTitle className="text-lg font-bold">Acme Creators</CardTitle>
            <div className="text-sm text-muted-foreground">1.2M subscribers</div>
          </div>
        </div>
        <Button variant="outline" size="sm">
          <PlusIcon className="mr-2 h-4 w-4" />
          Subscribe
        </Button>
      </CardHeader>
      <CardContent className="flex flex-col items-center justify-center gap-4">
        <div className="flex flex-col items-center justify-center w-full">
          <p>
            Acme Creators is a popular YouTube channel that focuses on creating high-quality content for the web
            development community.
          </p>
        </div>
        <div className="flex items-center justify-between w-full">
          <div className="flex flex-col items-center justify-center w-1/2">
            <div className="flex items-center gap-2">
              <VideoIcon className="mr-2 h-5 w-5 text-muted-foreground" />
              <div>
                <div className="font-medium">Video Count</div>
                <div className="text-sm text-muted-foreground">1,234</div>
              </div>
            </div>
          </div>
          <div className="flex flex-col items-center justify-center w-1/2">
            <div className="flex items-center justify-center gap-2">
              <ThumbsUpIcon className="mr-2 h-5 w-5 text-muted-foreground" />
              <div>
                <div className="font-medium">Saturation Score</div>
                <div className="text-sm text-muted-foreground">987K</div>
              </div>
            </div>
          </div>
        </div>
        <div className="flex items-center justify-between w-full">
          <div className="flex flex-col items-center justify-center w-1/2">
            <div className="flex items-center gap-2">
              <EyeIcon className="mr-2 h-5 w-5 text-muted-foreground" />
              <div>
                <div className="font-medium">View Count</div>
                <div className="text-sm text-muted-foreground">123M</div>
              </div>
            </div>
          </div>
          <div className="flex flex-col items-center justify-center w-1/2">
            <div className="flex items-center justify-center gap-2">
              <CalendarIcon className="mr-2 h-5 w-5 text-muted-foreground" />
              <div>
                <div className="font-medium">Date Joined</div>
                <div className="text-sm text-muted-foreground">2015</div>
              </div>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}

function CalendarIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  )
}

function EyeIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7Z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}
function PlusIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}
function ThumbsUpIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7 10v12" />
      <path d="M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2h0a3.13 3.13 0 0 1 3 3.88Z" />
    </svg>
  )
}
function VideoIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m16 13 5.223 3.482a.5.5 0 0 0 .777-.416V7.87a.5.5 0 0 0-.752-.432L16 10.5" />
      <rect x="2" y="6" width="14" height="12" rx="2" />
    </svg>
  )
}
